Update sbt-git to 3.0.0-RC1 (#396)
sbt-git 2.2.0 uses JGit 5.13, which doesn't support git worktrees. In a
worktree, loading a build that uses sbt-softwaremill-publish fails with:

```
org.eclipse.jgit.errors.NoWorkTreeException: Bare Repository has neither a working tree, nor an index
```

sbt-git 3.0.0-RC1 uses JGit 7.7, which supports worktrees. Tested in an
ox worktree: the build loads and the git-based `version` is correct.